### ISSUE TITLE
`diag_data` matching with missing values

### ISSUE THREAD

**Issue by hafen** [d3m-purdue/d3mLm#1]
When fitting models for data that has missing values, we want to be able to match the resulting `diag_data` back up with the data from which the model was generated. `broom::augment()` needs the original data to be able to do this.

```r
x <- runif(100)
y <- x + rnorm(100, sd = 0.1)
y[15] <- NA
d <- data.frame(x = x, y = y)

mod <- lm(y ~ x, data = d, na.action = na.exclude)

nrow(broom::augment(mod))
nrow(broom::augment(mod, newdata = d))
```

**Comment by schloerke** [comment]
25d0305f126aefdea496d61766d25bdff321a768
